### ISSUE TITLE
Add /players command

### ISSUE THREAD

**Issue by MykeMyke** [OperationXen/UnseenServant#210]
Add a /players command that reads the game channel and looks up the current players for that game to @ them with the inputted message. Whisper to user if not a valid game channel.

**Comment by OperationXen** [comment]
Can't you just use @channel for this?

**Comment by MykeMyke** [comment]
There is no discord command to ping a channel. When I just pulled up @everyone it warned of notifying 833 users, which isn't healthy (we've had reports of being pinged in channels that people don't have access too despite it not supposed to work in that way.

**Comment by MykeMyke** [comment]
Need for this has reared its head again with the epic in just over a week... request prioritisation if relatively straightforward.
