### ISSUE TITLE
Add command to remove all users from specified roles - for events

### ISSUE THREAD

**Issue by MykeMyke** [OperationXen/UnseenServant#271]
The following roles need to be "reset" after an event. @EventsCoordinator should have permission for a /reset_event_roles command which shall remove all members for:

- Event Staff
- Event DM
- Event Table Captains
- Event Participants

A confirmation dialogue is essential!

Is the following a useful starting point?
<img width="330" alt="image" src="https://github.com/OperationXen/UnseenServant/assets/72384771/3bd7ab69-d69a-452d-b96b-f00154de1dd1">

**Comment by OperationXen** [comment]
Well, the issue is clear enough, but that's javascript...
