### ISSUE TITLE
Add commands for event participants to self assign roles

### ISSUE THREAD

**Issue by MykeMyke** [OperationXen/UnseenServant#272]
Add command /add_to_event and /drop_from_event which can be run by anybody and adds / removes the role Event Participant
Add command /table_captain with argument for discord alias to add the role Event Table Captain. Optional argument for remove. This command should be able to be run by anybody with the role Event Staff, Event DM or Event Table Captain.

**Comment by OperationXen** [comment]
Role management requires a permissions update, which is a manual process - this deployment could go *sproing*
