### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by OperationXen** [OperationXen/UnseenServant#346]

**Comment by OperationXen** [comment]
Seems to be caused by request to logout endpoint not containing auth cookies

**Comment by OperationXen** [comment]
Client side issue fixed, now struggling with CSRF errors

**Comment by gludington** [comment]
csrf issues are caused by the csrf cookie token being set incorrectly.

As for the logout, even in my local dev, the sessionid cookie was not being deleted, despite the django docs saying they should be.

**Comment by OperationXen** [comment]
I chased this down and we were missing a body on the axios request to logout, so it was sending the options config as the body instead of using it as config...
