### ISSUE TITLE
Game Channel not created automatically when crossing 5 day threshold

### ISSUE THREAD

**Issue by MykeMyke** [OperationXen/UnseenServant#487]
I created 2 test games - one inside 5 days, one outwith. Neither proc'd the game channel to be automatically created. I restarted the bot in putty, and still don't see the channels in the Django "game channel" view.

**Comment by OperationXen** [comment]
Investigating the logs it looks like the channel creation controller is failing to find an expected message in a channel it has just created and may be crashing at the point that it attempts to re-associate to existing channels. Will investigate further
